from pathlib import Path

p = Path('index.html')
text = p.read_text(encoding='utf-8')

old_range = "function statusRange(reset=false){const from=$('#statusFrom'),to=$('#statusTo'),today=new Date();if(reset||!from.value){const first=new Date(today.getFullYear(),today.getMonth(),1);from.value=dateInputValue(first)}if(reset||!to.value)to.value=dateInputValue(today);if(from.value>to.value){toast('From Date, To Date se badi nahi ho sakti');return null}return{start:new Date(from.value+'T00:00:00').toISOString(),end:new Date(to.value+'T23:59:59.999').toISOString()}}"
new_range = "function statusRange(reset=false){const from=$('#statusFrom'),to=$('#statusTo'),parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).filter(x=>x.type!=='literal').map(x=>[x.type,x.value])),todayValue=`${parts.year}-${parts.month}-${parts.day}`;if(reset||!from.value)from.value=`${parts.year}-${parts.month}-01`;if(reset||!to.value)to.value=todayValue;if(from.value>to.value){toast('From Date, To Date se badi nahi ho sakti');return null}const start=new Date(from.value+'T00:00:00+05:30'),endStart=new Date(to.value+'T00:00:00+05:30'),end=new Date(endStart.getTime()+86400000);return{start:start.toISOString(),end:end.toISOString()}}"

old_stats = "async function loadCallStats(){const range=statusRange();if(!range)return;const {start,end}=range;let pending=db.from('crm_institute_call_state').select('*',{count:'exact',head:true}).is('last_status',null),follow=db.from('crm_institute_call_state').select('*',{count:'exact',head:true}).not('next_call_at','is',null).gte('next_call_at',start).lte('next_call_at',end),notReach=db.from('crm_call_logs').select('*',{count:'exact',head:true}).eq('status','Not Reachable').gte('created_at',start).lte('created_at',end),calls=db.from('crm_call_logs').select('*',{count:'exact',head:true}).gte('created_at',start).lte('created_at',end);if(isAdmin()){const staff=$('#callStaffFilter')?.value;if(staff){pending=pending.eq('assigned_to',staff);follow=follow.eq('assigned_to',staff);notReach=notReach.eq('staff_id',staff);calls=calls.eq('staff_id',staff)}else{pending=pending.not('assigned_to','is',null);follow=follow.not('assigned_to','is',null)}}const [p,f,n,t]=await Promise.all([pending,follow,notReach,calls]);const error=p.error||f.error||n.error||t.error;if(error){toast(error.message);return}$('#callPendingCount').textContent=(p.count||0).toLocaleString();$('#callTodayCount').textContent=(t.count||0).toLocaleString();$('#callFollowCount').textContent=(f.count||0).toLocaleString();$('#callNotReachCount').textContent=(n.count||0).toLocaleString()}"
new_stats = "async function loadCallStats(){const range=statusRange();if(!range)return;const {start,end}=range;let pending=db.from('crm_institute_call_state').select('*',{count:'exact',head:true}).is('last_status',null),follow=db.from('crm_institute_call_state').select('*',{count:'exact',head:true}).not('next_call_at','is',null).gte('next_call_at',start).lt('next_call_at',end),notReach=db.from('crm_call_logs').select('*',{count:'exact',head:true}).eq('status','Not Reachable').gte('created_at',start).lt('created_at',end),calls=db.from('crm_call_logs').select('*',{count:'exact',head:true}).gte('created_at',start).lt('created_at',end);if(isAdmin()){const staff=$('#callStaffFilter')?.value;if(staff){pending=pending.eq('assigned_to',staff);follow=follow.eq('assigned_to',staff);notReach=notReach.eq('staff_id',staff);calls=calls.eq('staff_id',staff)}else{pending=pending.not('assigned_to','is',null);follow=follow.not('assigned_to','is',null)}}else{pending=pending.eq('assigned_to',S.user.id);follow=follow.eq('assigned_to',S.user.id);notReach=notReach.eq('staff_id',S.user.id);calls=calls.eq('staff_id',S.user.id)}const [p,f,n,t]=await Promise.all([pending,follow,notReach,calls]);const error=p.error||f.error||n.error||t.error;if(error){toast(error.message);return}$('#callPendingCount').textContent=(p.count||0).toLocaleString();$('#callTodayCount').textContent=(t.count||0).toLocaleString();$('#callFollowCount').textContent=(f.count||0).toLocaleString();$('#callNotReachCount').textContent=(n.count||0).toLocaleString()}"

if old_range not in text:
    raise SystemExit('statusRange source not found')
if old_stats not in text:
    raise SystemExit('loadCallStats source not found')

text = text.replace(old_range, new_range, 1)
text = text.replace(old_stats, new_stats, 1)
p.write_text(text, encoding='utf-8')
