from pathlib import Path

p=Path('index.html')
text=p.read_text(encoding='utf-8')
marker='data-university-tab="feesettings"'
if marker in text:
    raise SystemExit('already applied')

old='''  <div class="university-detail-tabs" role="tablist" aria-label="University detail sections">\n    <button type="button" class="university-detail-tab" data-university-tab="fee">Fee Detail</button>\n    <button type="button" class="university-detail-tab" data-university-tab="approval">Approval</button>\n    <button type="button" class="university-detail-tab active" data-university-tab="info">University Info</button>\n  </div>\n  <section class="card university-detail-panel" data-university-panel="fee">\n    <div class="toolbar"><div><h2>Fee Detail</h2><p class="university-detail-note">Admin ke saved departments, columns, calculations aur courses yahan live dikhte hain.</p></div><button id="refreshFeeBuilder" class="btn secondary" type="button">Refresh</button></div>\n    <div id="feeAdminTools" class="fee-admin-tools admin-only">\n      <div class="fee-admin-actions"><button id="addFeeDepartment" class="btn primary" type="button">+ Department</button><button id="addFeeColumn" class="btn secondary" type="button">+ Column</button></div>\n      <p class="fee-builder-note">Formula example: <b>fees_per_year * year</b> or <b>total * 0.4</b>. Column Key formula mein use hota hai.</p>\n      <div id="feeColumnManager" class="fee-column-manager"></div>\n    </div>\n    <div id="feeBuilderHost"><p class="empty">Fee details loading...</p></div>\n  </section>'''

new='''  <div class="university-detail-tabs" role="tablist" aria-label="University detail sections">\n    <button type="button" class="university-detail-tab" data-university-tab="fee">Fee Detail</button>\n    <button type="button" class="university-detail-tab admin-only" data-university-tab="feesettings">Fee Settings</button>\n    <button type="button" class="university-detail-tab" data-university-tab="approval">Approval</button>\n    <button type="button" class="university-detail-tab active" data-university-tab="info">University Info</button>\n  </div>\n  <section class="card university-detail-panel" data-university-panel="fee">\n    <div class="toolbar"><div><h2>Fee Detail</h2><p class="university-detail-note">Admin ke saved departments, columns, calculations aur courses yahan live dikhte hain.</p></div><div class="fee-admin-actions"><button id="addFeeDepartment" class="btn primary admin-only" type="button">+ Department</button><button id="refreshFeeBuilder" class="btn secondary" type="button">Refresh</button></div></div>\n    <div id="feeBuilderHost"><p class="empty">Fee details loading...</p></div>\n  </section>\n  <section class="card university-detail-panel admin-only" data-university-panel="feesettings">\n    <div class="toolbar"><div><h2>Fee Settings</h2><p class="university-detail-note">Columns aur calculations ko yahan manage karein. Yahan ki settings Fee Detail table par apply hongi.</p></div><button id="addFeeColumn" class="btn primary" type="button">+ Column</button></div>\n    <div id="feeAdminTools" class="fee-admin-tools admin-only">\n      <p class="fee-builder-note">Formula example: <b>fees_per_year * year</b> or <b>total * 0.4</b>. Column Key formula mein use hota hai.</p>\n      <div id="feeColumnManager" class="fee-column-manager"></div>\n    </div>\n  </section>'''

if old not in text:
    raise SystemExit('fee section target not found')
text=text.replace(old,new,1)

old_js='''$('#addFeeDepartment')?.addEventListener('click',addFeeDepartment);$('#addFeeColumn')?.addEventListener('click',addFeeColumn);$('#refreshFeeBuilder')?.addEventListener('click',loadFeeBuilder);document.querySelector('[data-university-tab="fee"]')?.addEventListener('click',loadFeeBuilder);document.querySelector('[data-page="universitydetail"]')?.addEventListener('click',()=>setTimeout(()=>{if(document.querySelector('[data-university-tab="fee"]')?.classList.contains('active'))loadFeeBuilder()},0));'''
new_js='''$('#addFeeDepartment')?.addEventListener('click',addFeeDepartment);$('#addFeeColumn')?.addEventListener('click',addFeeColumn);$('#refreshFeeBuilder')?.addEventListener('click',loadFeeBuilder);document.querySelector('[data-university-tab="fee"]')?.addEventListener('click',loadFeeBuilder);document.querySelector('[data-university-tab="feesettings"]')?.addEventListener('click',loadFeeBuilder);document.querySelector('[data-page="universitydetail"]')?.addEventListener('click',()=>setTimeout(()=>{if(document.querySelector('[data-university-tab="fee"]')?.classList.contains('active'))loadFeeBuilder()},0));'''
if old_js not in text:
    raise SystemExit('fee listener target not found')
text=text.replace(old_js,new_js,1)

p.write_text(text,encoding='utf-8')
