-- Calling CRM schema for Supabase
-- Run this file in Supabase Dashboard > SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.crm_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text not null,
  role text not null default 'staff' check (role in ('admin','staff')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.crm_profiles add column if not exists joining_date date;
alter table public.crm_profiles add column if not exists post text;
alter table public.crm_profiles add column if not exists office_location_id uuid references public.crm_office_locations(id) on delete set null;

create table if not exists public.crm_institutes (
  id uuid primary key default gen_random_uuid(),
  serial_no bigint generated by default as identity unique,
  institute_name text not null,
  owner_name text,
  address text,
  location text,
  state text,
  country text not null default 'India',
  mobile_no text,
  email_id text,
  data_source text,
  assigned_to uuid references public.crm_profiles(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.crm_office_locations (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.crm_call_logs (
  id uuid primary key default gen_random_uuid(),
  institute_id uuid not null references public.crm_institutes(id) on delete cascade,
  staff_id uuid not null references public.crm_profiles(id) on delete restrict default auth.uid(),
  status text not null check (status in ('Interested','Follow Up','Not Interested','Not Reachable','Call Back')),
  remarks text,
  next_call_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.crm_is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.crm_profiles where id = auth.uid() and role = 'admin' and active); $$;

create or replace function public.crm_handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.crm_profiles(id, full_name, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name',''),
    coalesce(new.email,''),
    case when lower(coalesce(new.email,'')) = 'sengoladmission@gmail.com' then 'admin' else 'staff' end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists crm_on_auth_user_created on auth.users;
create trigger crm_on_auth_user_created
after insert on auth.users for each row execute procedure public.crm_handle_new_user();

create or replace function public.crm_set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists crm_institutes_updated_at on public.crm_institutes;
create trigger crm_institutes_updated_at before update on public.crm_institutes
for each row execute procedure public.crm_set_updated_at();

alter table public.crm_profiles enable row level security;
alter table public.crm_institutes enable row level security;
alter table public.crm_call_logs enable row level security;
alter table public.crm_office_locations enable row level security;

create policy "crm profile self read" on public.crm_profiles for select to authenticated
using (id = auth.uid() or public.crm_is_admin());
create policy "crm admin manages profiles" on public.crm_profiles for update to authenticated
using (public.crm_is_admin()) with check (public.crm_is_admin());

create policy "crm admin deletes profiles" on public.crm_profiles for delete to authenticated
using (public.crm_is_admin());

create policy "crm staff sees assigned rows" on public.crm_institutes for select to authenticated
using (deleted_at is null and (public.crm_is_admin() or assigned_to = auth.uid()));
create policy "crm admin inserts rows" on public.crm_institutes for insert to authenticated
with check (public.crm_is_admin());
create policy "crm staff edits assigned rows" on public.crm_institutes for update to authenticated
using (public.crm_is_admin() or assigned_to = auth.uid())
with check (public.crm_is_admin() or assigned_to = auth.uid());
create policy "crm admin deletes rows" on public.crm_institutes for delete to authenticated
using (public.crm_is_admin());

create policy "crm users see office locations" on public.crm_office_locations for select to authenticated using (true);
create policy "crm admin manages office locations" on public.crm_office_locations for all to authenticated using (public.crm_is_admin()) with check (public.crm_is_admin());

create policy "crm staff sees own call logs" on public.crm_call_logs for select to authenticated
using (public.crm_is_admin() or staff_id = auth.uid());
create policy "crm staff creates own call logs" on public.crm_call_logs for insert to authenticated
with check ((staff_id = auth.uid() and exists(select 1 from public.crm_institutes i where i.id = institute_id and i.assigned_to = auth.uid())) or public.crm_is_admin());
create policy "crm staff edits own call logs" on public.crm_call_logs for update to authenticated
using (public.crm_is_admin() or staff_id = auth.uid())
with check (public.crm_is_admin() or staff_id = auth.uid());

create index if not exists crm_institutes_assigned_to_idx on public.crm_institutes(assigned_to) where deleted_at is null;
create index if not exists crm_institutes_location_idx on public.crm_institutes(location);
create index if not exists crm_institutes_state_idx on public.crm_institutes(state);
create index if not exists crm_institutes_mobile_idx on public.crm_institutes(mobile_no);
create index if not exists crm_call_logs_staff_idx on public.crm_call_logs(staff_id);
create index if not exists crm_call_logs_institute_idx on public.crm_call_logs(institute_id);
